name: Automation - Create Tag for Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag-for-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Create tag for release
        env:
          # We are deliberately not using the default secrets.GITHUB_TOKEN here, since pull requests from that token do
          # not trigger subsequent workflows, see
          # https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow#triggering-a-workflow-from-a-workflow.
          # I.e., creating and pushing the tag would not trigger the workflow .github/workflows/build.yml. We do need to
          # trigger the workflow for the tag we are creating here though, as the job publish-stable from build.yaml
          # actually creates the release and uploads the assets.
          # See https://github.com/open-telemetry/community/blob/9eaa934620638a2f5537d3d74372b389098a8f5e/assets.md#otelbot.
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: .github/workflows/scripts/create-tag-for-release.sh
